name: Check

on: pull_request

jobs:
  fmt:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./webapp/go    # アプリのディレクトリに合わせる
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16.5'
      - run: go fmt main.go               # アプリの.goファイルをすべて記載(半角スペース区切り)
  vet:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./webapp/go    # アプリのディレクトリに合わせる
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16.5'
      - run: go vet main.go               # アプリの.goファイルをすべて記載(半角スペース区切り)
  build:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./webapp/go    # TODO アプリのディレクトリに合わせる
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.16.5'
      - run: go build -a main.go